#!/usr/bin/env bash
# choose -- Presents an interactive dialog to select a line from given command's output
# $ choose COMMAND [ARG...]
##
set -euo pipefail

[[ $# -gt 0 ]] || usage "$0" "Missing COMMAND"

# make sure we have the terminal
exec 3>&1 </dev/tty >/dev/tty

# run given COMMAND to get the options
eval "set -- $("$@" | @sh)"

# ask to select a line
select line in "$@"; do
    case $line in
        "") # retry
            ;;
        *)
            # output chosen line to stdout
            echo "$line" >&3
            exit 0
    esac
done
false
