#!/usr/bin/env bash
# RUN-uti -- Runs command in the container interactively with a tty as $DKR_USER
# $ RUN-uti COMMAND [ARG...]
##
set -euo pipefail

: ${DKR_USER:?}
[[ $# -gt 0 ]] || usage "$0" "Missing COMMAND"

# switch user for running given command with RUN-ti
exec RUN-ti su "$DKR_USER" -c "$(@sh "$@")"
