#!/usr/bin/env bash
# RUN-u -- Runs given command in the container as $DKR_USER
# $ DKR_USER=$USER  RUN-u COMMAND [ARG...]
##
set -euo pipefail

: ${DKR_USER:?}
[[ $# -gt 0 ]] || usage "$0" "Missing COMMAND"

# switch user for running given command
exec RUN su "$DKR_USER" -c "$(@sh "$@")"
